# action.yml
name: 'Git Auto Merger'
description: 'A Github Action that tries to merge a base branch into branches you specify and sends an alert if it is not able to do that'
inputs:
  base-branch:  # id of input
    description: 'The base branch that you would like to merge into the other branches (eg. develop)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base-branch }}
